id: t1d-exchange
canonical: http://t1dexchange.org/fhir
name: T1DExchangeIG
title: T1D Exchange Implementation Guide
description: FHIR Implementation Guide for T1D Exchange Data Specification
status: draft
version: 0.3.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: STU1
license: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
publisher:
  name: T1D Exchange
  url: https://t1dexchange.org/

parameters:
  show-inherited-invariants: false
  usage-stats-opt-out: false
  excludexml: false
  excludejson: false
  excludettl: true
  excludemap: true
  pin-canonicals: pin-all
  shownav: 'true'

pages:
  index.md:
    title: Home
  overview.md:
    title: Overview of Implementation
  profiles.md:
    title: Profiles
  terminology.md:
    title: Terminology
  bundles.md:
    title: Bundle Patterns
  examples.md:
    title: Examples
  implementation.md:
    title: Technical Implementation
  quality-metrics.md:
    title: Quality Metrics
  workflows.md:
    title: Implementation Workflows
  security.md:
    title: Security & Best Practices
  mapping.md:
    title: Variable Mapping
  cgm-comparison.md:
    title: CGM IG Comparison
  downloads.md:
    title: Downloads

menu:
  Home: index.html
  Guidance:
    Overview of Implementation: overview.html
    Profiles: profiles.html
    Terminology: terminology.html
    Examples: examples.html
    Technical Implementation: implementation.html
    Quality Metrics: quality-metrics.html
    Implementation Workflows: workflows.html
    Bundle Patterns: bundles.html
    Variable Mapping: mapping.html
    Security & Best Practices: security.html
    CGM IG Comparison: cgm-comparison.html
  Artifacts:
    Profiles: artifacts.html#1
    Extensions: artifacts.html#2
    Value Sets: artifacts.html#3
    Code Systems: artifacts.html#4
    Examples: artifacts.html#5
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/
    Downloads: downloads.html